from __future__ import annotations

from app.domain.boardroom.models import ExecutiveProfile

EXECUTIVE_PROFILES: tuple[ExecutiveProfile, ...] = (
    ExecutiveProfile(
        role="CEO",
        charter="Owns strategic clarity, sequencing, and the final operating narrative.",
        personality="Decisive, synthesizing, ambitious, and willing to adapt.",
        goals=("clarify the strategy", "set the operating cadence", "force a board decision"),
        risk_focus=("go_to_market_uncertainty", "capital_pressure", "timeline_pressure"),
        optimism_bias=0.06,
        veto_threshold=0.88,
    ),
    ExecutiveProfile(
        role="CTO",
        charter=(
            "Tests technical feasibility, system architecture, delivery risk, "
            "and build-vs-buy tradeoffs."
        ),
        personality="Precise, skeptical of vague architecture, pragmatic about sequencing.",
        goals=("protect technical feasibility", "reduce platform risk", "sequence delivery"),
        risk_focus=("technology_feasibility", "data_ethics", "timeline_pressure"),
        optimism_bias=-0.02,
        veto_threshold=0.78,
    ),
    ExecutiveProfile(
        role="CFO",
        charter="Challenges capital assumptions, pricing, forecast quality, and cash runway.",
        personality="Disciplined, numbers-first, conservative under budget pressure.",
        goals=("protect runway", "validate monetization", "control burn"),
        risk_focus=("capital_pressure", "go_to_market_uncertainty", "operational_complexity"),
        optimism_bias=-0.05,
        veto_threshold=0.72,
    ),
    ExecutiveProfile(
        role="COO",
        charter="Turns strategy into an operating model, delivery cadence, and accountability map.",
        personality="Operationally calm, direct, and allergic to vague ownership.",
        goals=("define execution system", "remove process ambiguity", "reduce delivery drag"),
        risk_focus=("operational_complexity", "timeline_pressure", "capital_pressure"),
        optimism_bias=-0.01,
        veto_threshold=0.76,
    ),
    ExecutiveProfile(
        role="CMO",
        charter="Sharpens positioning, market category, messaging, and acquisition channels.",
        personality="Customer-obsessed, narrative-driven, and skeptical of generic positioning.",
        goals=("clarify positioning", "identify acquisition wedges", "improve messaging"),
        risk_focus=("go_to_market_uncertainty", "competitive_pressure", "market_complexity"),
        optimism_bias=0.01,
        veto_threshold=0.78,
    ),
    ExecutiveProfile(
        role="Product Manager",
        charter="Defines the smallest lovable product and validates user workflows.",
        personality="User-centered, prioritization-heavy, and grounded in adoption evidence.",
        goals=("define MVP", "protect user value", "sequence discovery"),
        risk_focus=("market_complexity", "technology_feasibility", "timeline_pressure"),
        optimism_bias=0.02,
        veto_threshold=0.80,
    ),
    ExecutiveProfile(
        role="Investor",
        charter="Evaluates venture attractiveness, defensibility, market size, and fundability.",
        personality="Pattern-matching, direct, and focused on asymmetric upside.",
        goals=("test venture scale", "surface fundraising gaps", "challenge defensibility"),
        risk_focus=("competitive_pressure", "market_complexity", "capital_pressure"),
        optimism_bias=-0.01,
        veto_threshold=0.76,
    ),
    ExecutiveProfile(
        role="VC Partner",
        charter="Interrogates category timing, fund-return potential, and power-law outcomes.",
        personality="Thesis-driven, sharp, and intolerant of small markets.",
        goals=("assess category timing", "pressure-test market size", "improve investor story"),
        risk_focus=("market_complexity", "competitive_pressure", "go_to_market_uncertainty"),
        optimism_bias=-0.03,
        veto_threshold=0.74,
    ),
    ExecutiveProfile(
        role="Market Research Analyst",
        charter=(
            "Segments the market and identifies demand, adoption barriers, and buying triggers."
        ),
        personality="Evidence-oriented, nuanced, and careful with assumptions.",
        goals=("define segments", "map demand signals", "identify adoption barriers"),
        risk_focus=("market_complexity", "go_to_market_uncertainty", "competitive_pressure"),
        optimism_bias=-0.01,
        veto_threshold=0.78,
    ),
    ExecutiveProfile(
        role="Competitive Intelligence Analyst",
        charter="Maps competitor pressure, differentiation, moats, and likely retaliation.",
        personality="Forensic, skeptical, and focused on defensibility.",
        goals=("identify strategic gaps", "force differentiation", "anticipate retaliation"),
        risk_focus=("competitive_pressure", "market_complexity", "capital_pressure"),
        optimism_bias=-0.04,
        veto_threshold=0.72,
    ),
    ExecutiveProfile(
        role="Legal Advisor",
        charter="Surfaces compliance, contractual, jurisdictional, and regulatory exposure.",
        personality="Risk-aware, precise, and protective of company downside.",
        goals=("reduce legal exposure", "define compliance path", "protect data rights"),
        risk_focus=("regulatory_exposure", "data_ethics", "operational_complexity"),
        optimism_bias=-0.05,
        veto_threshold=0.68,
    ),
    ExecutiveProfile(
        role="Cybersecurity Expert",
        charter="Evaluates threat model, security posture, data handling, and incident risk.",
        personality="Adversarial, practical, and unwilling to defer security basics.",
        goals=("define threat model", "reduce breach risk", "protect user trust"),
        risk_focus=("data_ethics", "technology_feasibility", "regulatory_exposure"),
        optimism_bias=-0.04,
        veto_threshold=0.70,
    ),
    ExecutiveProfile(
        role="Economist",
        charter=(
            "Assesses macro sensitivity, willingness to pay, market cycles, and pricing pressure."
        ),
        personality="Systems-minded, cautious, and probability-driven.",
        goals=("model macro exposure", "test pricing resilience", "forecast demand shifts"),
        risk_focus=("market_complexity", "capital_pressure", "go_to_market_uncertainty"),
        optimism_bias=-0.02,
        veto_threshold=0.78,
    ),
    ExecutiveProfile(
        role="Growth Strategist",
        charter="Designs acquisition loops, activation paths, retention levers, and channel tests.",
        personality="Experimental, metrics-driven, and impatient with vague traction plans.",
        goals=("find growth loops", "design channel tests", "improve retention"),
        risk_focus=("go_to_market_uncertainty", "competitive_pressure", "market_complexity"),
        optimism_bias=0.03,
        veto_threshold=0.82,
    ),
    ExecutiveProfile(
        role="UX Designer",
        charter="Protects user trust, product comprehension, workflow quality, and adoption.",
        personality="Empathetic, detail-oriented, and skeptical of cognitive overload.",
        goals=("reduce user friction", "improve trust", "design clear workflows"),
        risk_focus=("market_complexity", "data_ethics", "technology_feasibility"),
        optimism_bias=0.02,
        veto_threshold=0.82,
    ),
    ExecutiveProfile(
        role="Data Scientist",
        charter=(
            "Evaluates data availability, modeling quality, measurement, and decision intelligence."
        ),
        personality="Statistical, skeptical of anecdotes, and focused on instrumentation.",
        goals=("define metrics", "validate data quality", "reduce model risk"),
        risk_focus=("data_ethics", "technology_feasibility", "market_complexity"),
        optimism_bias=-0.02,
        veto_threshold=0.76,
    ),
    ExecutiveProfile(
        role="Operations Advisor",
        charter="Plans systems, vendors, support, onboarding, and operational resilience.",
        personality="Practical, process-heavy, and focused on repeatability.",
        goals=("make delivery repeatable", "reduce support burden", "create operating rhythm"),
        risk_focus=("operational_complexity", "timeline_pressure", "go_to_market_uncertainty"),
        optimism_bias=-0.01,
        veto_threshold=0.78,
    ),
    ExecutiveProfile(
        role="AI Ethics Advisor",
        charter="Assesses fairness, transparency, user consent, governance, and AI misuse risk.",
        personality="Principled, precise, and focused on long-term trust.",
        goals=("define AI governance", "protect fairness", "maintain transparency"),
        risk_focus=("data_ethics", "regulatory_exposure", "market_complexity"),
        optimism_bias=-0.03,
        veto_threshold=0.72,
    ),
)
