export const ENTERPRISE_COPY = {
  nav: {
    enterprise: "Enterprise",
    intelligence: "Intelligence",
    operations: "Ops",
    command: "Command palette",
    notifications: "Notifications"
  },
  dashboard: {
    title: "Enterprise Workspace",
    subtitle: "Organization activity, approvals, tasks, and executive signals",
    organization: "Organization",
    departments: "Departments",
    teams: "Teams",
    users: "Users",
    pendingApprovals: "Pending approvals",
    tasks: "Tasks",
    activity: "Board activity",
    calendar: "Upcoming reviews",
    analytics: "Analytics",
    executiveSignals: "Executive signals"
  },
  empty: {
    approvals: "No approvals are waiting.",
    tasks: "No open tasks yet.",
    activity: "Activity will appear after meetings and workflow changes.",
    calendar: "No scheduled reviews yet."
  },
  loading: {
    dashboard: "Loading organization workspace...",
    intelligence: "Loading enterprise intelligence...",
    approvals: "Checking pending approvals...",
    activity: "Reading audit trail..."
  },
  errors: {
    workspace: "Workspace data could not be loaded.",
    intelligence: "Enterprise intelligence could not be loaded.",
    offline: "You appear to be offline. Desktop actions will reconnect when the backend is available."
  },
  intelligence: {
    title: "Executive Intelligence",
    subtitle: "Memory, graph, assistant, documents, workflows, and release health",
    memory: "Executive memory",
    graph: "Knowledge graph",
    analytics: "Advanced analytics",
    assistant: "Executive assistant",
    documents: "Document intelligence",
    workflows: "Workflow automation",
    observability: "Observability",
    collaboration: "Collaboration",
    search: "Global search",
    questionPlaceholder: "Ask about risks, approvals, suppliers, rejected decisions...",
    searchPlaceholder: "Search all enterprise records",
    upload: "Import document",
    runWorkflow: "Run workflow",
    ask: "Ask",
    empty: "No records yet.",
    fallback: "Compatibility mode",
    noGraph: "No graph nodes are available yet."
  },
  operations: {
    title: "Operations",
    subtitle: "Live reliability, queue, provider, and platform health for enterprise deployments",
    loading: "Loading operations dashboard...",
    refresh: "Refresh",
    queueRefresh: "Queue analytics refresh",
    loadError: "Operations dashboard could not be loaded.",
    jobError: "Operations job could not be queued.",
    jobQueued: "Job queued",
    lastUpdated: "Last updated",
    apiLatency: "API latency",
    p95Latency: "p95 latency",
    requests: "Requests",
    activeRequests: "Active requests",
    activeUsers: "Active users",
    liveSessions: "Open sessions",
    memory: "Memory",
    processMemory: "Process memory",
    dependencies: "Dependencies",
    storage: "Storage",
    cache: "Cache",
    queueSize: "Queue size",
    deadLetter: "Dead letter",
    jobs: "Background jobs",
    schedules: "Schedules",
    providers: "Providers",
    plugins: "Plugins",
    registeredPlugins: "Registered plugins",
    pluginTypes: "Plugin types",
    versioning: "API versioning",
    apiVersions: "v1 + v2 preview",
    emptyJobs: "No background jobs are queued.",
    emptySchedules: "No schedules have been created.",
    emptyStatus: "No status records are available.",
    noAdditionalDetail: "No additional detail",
    nextRun: "Next run"
  }
} as const;
